[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "apex"
version = "3.0.0"
description = "The fastest memoizing and caching Python library written in Rust"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
keywords = ["caching", "cached", "cachebox", "cache", "in-memory-caching", "memoizing"]
authors = [
  {email = "awolverp@gmail.com"},
  {name = "awolverp"}
]

classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    'License :: OSI Approved :: MIT License',
    'Operating System :: POSIX :: Linux',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: MacOS',
    'Typing :: Typed',
]

[project.urls]
Homepage = 'https://github.com/awolverp/cachebox'
Homepage2 = 'https://github.com/Lovania-Networking-and-Software/apex'

[tool.maturin]
features = ["pyo3/extension-module"]
bindings = 'pyo3'
module-name = "apex._apex"
